# Configure main menu and social menu
#[[main]]
#identifier = "home"
#name = "Home"
#url = "/"
#[main.params]
#icon = "home"
#newtab = true

[[social]]
identifier = "github"
name = "GitHub"
url = "https://github.com/marcossaleseng/"

[social.params]
icon = "github-logo"

[[social]]
identifier = "linkedin"
name = "Linkedin"
url = "https://linkedin.com/in/marcos-sales-526252a3"

[social.params]
icon = "linkedin-logo"
